spring:
    application:
        name: youth-spring

    datasource:
        url: jdbc:mysql://43.201.1.223:3306/youth?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: youth_admin
        password: 1234

    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL8Dialect
        database: mysql

        hibernate:
            ddl-auto: none
            naming:
                strategy: org.hibernate.cfg.ImprovedNamingStrategy
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

        generate-ddl: false

        properties:
            hibernate:
                format_sql: true
                enable_lazy_load_no_trans: true
server:
  port: 5000


